### ISSUE TITLE
Error on node-gyp rebuild

### ISSUE THREAD

**Issue by paumartin** [MySiteApp/node-safari-push-notifications#19]
Hi!

Thanks for your work with this node module, it has been very useful :) 

We have just updated our base docker image based on Linux Alpine and Node to:

- SO: Linux Alpine 3.9
- Node Version: 12.4

And when installing safari push notifications (npm install), node-gyp rebuild is crashing when building pkcs7.cc file.

Notice that we have been using it with Linux Alpine 3.8 and Node 10 without problems until the update. 

We attach the stacktrace, I hope it helps! 

```
 safari-push-notifications@0.3.3 install /app/node_modules/safari-push-notifications
 node-gyp rebuild

make: Entering directory '/app/node_modules/safari-push-notifications/build'
  CXX(target) Release/obj.target/pkcs7/src/pkcs7.o
In file included from ../src/pkcs7.cc:14:
../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
../../nan/nan.h:2298:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
../src/pkcs7.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE Sign(Nan::NAN_METHOD_ARGS_TYPE)':
../src/pkcs7.cc:47:45: error: no matching function for call to 'v8::Value::ToObject()'
   Local<Object> certObj = info[0]->ToObject();
                                             ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate: 'v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const'
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/pkcs7.cc:56:45: error: no matching function for call to 'v8::Value::ToObject()'
   Local<Object> pKeyObj = info[1]->ToObject();
                                             ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate: 'v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const'
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/pkcs7.cc:65:45: error: no matching function for call to 'v8::Value::ToObject()'
   Local<Object> dataObj = info[2]->ToObject();
                                             ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate: 'v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const'
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/pkcs7.cc:81:55: error: no matching function for call to 'v8::Value::ToObject()'
     Local<Object> intermediateObj = info[3]->ToObject();
                                                       ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate: 'v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const'
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/pkcs7.cc: In function 'Nan::NAN_METHOD_RETURN_TYPE Verify(Nan::NAN_METHOD_ARGS_TYPE)':
../src/pkcs7.cc:149:43: error: no matching function for call to 'v8::Value::ToObject()'
   Local<Object> inObj = info[0]->ToObject();
                                           ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate: 'v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const'
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/pkcs7.cc:156:47: error: no matching function for call to 'v8::Value::ToObject()'
   Local<Object> sigObject = info[1]->ToObject();
                                               ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate: 'v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const'
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/pkcs7.cc:168:45: error: no matching function for call to 'v8::Value::ToObject()'
   Local<Object> certObj = info[2]->ToObject();
                                             ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate: 'v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const'
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/pkcs7.cc:178:49: error: no matching function for call to 'v8::Value::ToObject()'
     Local<Object> intermObj = info[3]->ToObject();
                                                 ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate: 'v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const'
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/pkcs7.cc:189:47: error: no matching function for call to 'v8::Value::ToObject()'
     Local<Object> rootObj = info[4]->ToObject();
                                               ^
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note: candidate: 'v8::MaybeLocal<v8::Object> v8::Value::ToObject(v8::Local<v8::Context>) const'
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2532:44: note:   candidate expects 1 argument, 0 provided
In file included from /root/.node-gyp/12.4.0/include/node/v8-internal.h:14,
                 from /root/.node-gyp/12.4.0/include/node/v8.h:25,
                 from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note: candidate: 'v8::Local<v8::Object> v8::Value::ToObject(v8::Isolate*) const'
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h:2546:35: note:   candidate expects 1 argument, 0 provided
                     Local<Object> ToObject(Isolate* isolate) const);
                                   ^~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8config.h:322:3: note: in definition of macro 'V8_DEPRECATE_SOON'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/pkcs7.cc:4:
../src/pkcs7.cc: At global scope:
/root/.node-gyp/12.4.0/include/node/node.h:556:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.node-gyp/12.4.0/include/node/node.h:590:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/pkcs7.cc:214:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(pkcs7, Init)
 ^~~~~~~~~~~
In file included from /root/.node-gyp/12.4.0/include/node/node.h:63,
                 from ../src/pkcs7.cc:4:
/root/.node-gyp/12.4.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
/root/.node-gyp/12.4.0/include/node/node_object_wrap.h:84:78:   required from here
/root/.node-gyp/12.4.0/include/node/v8.h:9817:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.node-gyp/12.4.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.node-gyp/12.4.0/include/node/v8.h:9817:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
make: *** [pkcs7.target.mk:107: Release/obj.target/pkcs7/src/pkcs7.o] Error 1
make: Leaving directory '/app/node_modules/safari-push-notifications/build'
gyp ERR! build error
gyp ERR! stack Error: 'make' failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.9.125-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/safari-push-notifications
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! safari-push-notifications@0.3.3 install: 'node-gyp rebuild'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the safari-push-notifications@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-18T15_26_26_536Z-debug.log
```

**Comment by ruizmarc** [comment]
Same problem here! :(

**Comment by Pinedo11** [comment]
We are also planning to upgrade our system, it would be great to have this issue fixed 🙂

**Comment by kobim** [comment]
you're totally right, [version 0.4.0](https://www.npmjs.com/package/safari-push-notifications/v/0.4.0) has just been published with support for node 12!

**Comment by ruizmarc** [comment]
Wow! You have been very quick! Thanks for your efforts :D
