### ISSUE TITLE
Still cannot deploy to aws beanstalk with error

### ISSUE THREAD

**Issue by aotol** [MySiteApp/node-safari-push-notifications#25]
Hi there,

I raised issue https://github.com/MySiteApp/node-safari-push-notifications/issues/24 earlier and I have tried both solution mentioned in:
https://github.com/lovell/sharp/issues/373#issuecomment-226849756
and
https://github.com/nodejs/node-gyp/issues/414#issuecomment-193574962

However, I am still not able to deploy safari push notification into aws beanstalk with the following error message. I noticed that this time the error is a bit changed. I didn't include my build or node_modules directory in my zip file when uploading.

  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! safari-push-notifications@0.4.0 install: `node-gyp rebuild`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the safari-push-notifications@0.4.0 install script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/ec2-user/.npm/_logs/2020-03-03T00_47_26_563Z-debug.log
  Not using a reverse proxy
  Running npm install:  /opt/elasticbeanstalk/node-install/node-v12.16.1-linux-x64/bin/npm
  Setting npm config jobs to 1
  npm config jobs set to 1
  Running npm with --production flag
  Failed to run npm install. Snapshot logs for more details.
  UTC 2020/03/03 00:47:26 cannot find application npm debug log at /tmp/deployment/application/npm-debug.log 
  
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
      main()
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
      node_version_manager.run_npm_install(options.app_path)
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
      self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
    File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
      raise e
  subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v12.16.1-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status 1 (Executor::NonZeroExitStatus)

[2020-03-03T00:47:26.586Z] ERROR [13572] : Command CMD-ConfigDeploy failed!

**Comment by aotol** [comment]
The problem is resolved with this workaround:
https://github.com/nodejs/node-gyp/issues/414#issuecomment-446404434
