### ISSUE TITLE
Cannot install in Node 14.7.3 and Alpine 3.14

### ISSUE THREAD

**Issue by ruizmarc** [MySiteApp/node-safari-push-notifications#39]
Hi,

It has been like two-three years using this lib (thanks for your work, your lib has been very useful for us!), however, we have recently updated to Node 14.7.3 and Alpine 3.14 and we are getting an error when building the Docker Image on Ubuntu Desktop (It works fine on MacOS) during the installation of this library. 

This is the image we use in our dockerfile:

`FROM node:14.17.3-alpine3.14`

And this is the error we are getting on ubuntu.

```Executing busybox-1.33.1-r2.trigger
OK: 244 MiB in 46 packages
> bcrypt@5.0.1 install /ptp/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build
[bcrypt] Success: "/ptp/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" is installed via remote
> safari-push-notifications@0.5.0 install /ptp/node_modules/safari-push-notifications
> node-gyp rebuild
make: Entering directory '/ptp/node_modules/safari-push-notifications/build'
make: printf: Operation not permitted
make: *** [pkcs7.target.mk:111: Release/obj.target/pkcs7/src/pkcs7.o] Error 127
make: Leaving directory '/ptp/node_modules/safari-push-notifications/build'
gyp ERR! build error
 

gyp 
ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack
     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack
     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

gyp ERR! System
 Linux 5.8.0-59-generic
gyp 
ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /ptp/node_modules/safari-push-notifications

gyp ERR! node -v v14.17.3
gyp ERR! node-gyp -v v5.1.0

gyp ERR! not ok 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})



npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! safari-push-notifications@0.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the safari-push-notifications@0.5.0 install script.
npm ERR!
 This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-19T09_09_53_205Z-debug.log
```

Can you help us with this? 

Thanks for your attention!

**Comment by ruizmarc** [comment]
Just if it can help someone, we have solved the issue. It was not a problem with the lib, but with alpine 3.14. For further information: https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2
